### ISSUE TITLE
[Enhancement] recipe detail response 수정

### ISSUE THREAD

**Issue by eogns47** [Recipic/Recipic-Server#70]
## 📝설명
recipe detail response 수정

## ✔️ TO-DO
- [x] 반환 재료값 id에서 name으로
- [x] comment는 따로 API로 (페이지네이션 위해)
- [x] 유저 프로필 추가
- [x] 브랜드명은 brand_name으로
