### ISSUE TITLE
[ISSUE] 알러지 재료 등록

### ISSUE THREAD

**Issue by knxxxn** [Recipic/Recipic-Server#97]
## 📝설명
알러지 등록, 알러지 재료 등록

## ✔️ TO-DO
- [ ] 알러지 종류 등록
- [ ] 알러지 종류에 따른 재료 분류
- [ ] 사용자가 선택한 알러지 재료 저장
